name: BabyEatsFood

fileGroups: [README.md, .gitignore, .swiftlint.yml, .swiftformat, project.yml]

options:
  deploymentTarget: 
    iOS: 16.0

settings:
  SWIFT_VERSION: 5.9
  CODE_SIGN_IDENTITY: iPhone Developer

include:
  - Modules/front.yml
  - Modules/api.yml
  - Modules/openFoodFactsNetwork.yml
  - Modules/services.yml

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    exactVersion: 7.9.1
  Nimble:
    url: https://github.com/Quick/Nimble
    exactVersion: 12.3.0
  RealmSwift:
    url: https://github.com/realm/realm-cocoa
    exactVersion: 10.43.0
  Swinject:
    url: https://github.com/Swinject/Swinject.git
    exactVersion: 2.8.4
  SwinjectAutoregistration:
    url: https://github.com/Swinject/SwinjectAutoregistration.git
    exactVersion: 2.8.3
  Lottie:
    url: git@github.com:airbnb/lottie-ios.git
    exactVersion: 4.3.3
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    exactVersion: 1.9.0
  ObjectMapper:
    url: https://github.com/tristanhimmelman/ObjectMapper
    exactVersion: 4.2.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    exactVersion: 6.6.0
